name: Deploy Dist
on: [push,workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v7
            -  name: Install Node 20
               uses: actions/setup-node@v7
               with:
                node-version: 20
            - name: print node version
              run: node -v
            - name: Install Dependencies
              run: npm ci
            - name: Run Tests
              run: npm run test
            
            



